
- name: Update Fargate Cluster
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Create task definition
    community.aws.ecs_taskdefinition:
      family: shelterly
      containers:
      - name: shelterly
        image: trevorskaggs/shelterly:010721prod3
        portMappings:
        - containerPort: 80
          hostPort: 80
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: /ecs/shelterly
            awslogs-region: us-east-2
            awslogs-stream-prefix: ecs
      launch_type: FARGATE
      cpu: 512
      memory: 1024
      execution_role_arn: "arn:aws:iam::363875932628:role/ecsTaskExecutionRole"
      state: present
      network_mode: awsvpc
  - name: Update service
    community.aws.ecs_service:
      state: present
      name: shelterly-dev
      launch_type: FARGATE
      cluster: shelterly
      task_definition: 'shelterly:35'
      desired_count: 1
      network_configuration:
        subnets:
        - subnet-03a18c8e8fb91d047
        - subnet-0d600acd5473461ab
        - subnet-096d0390725a021d4
        security_groups:
        - sg-018e52da071526267
        - sg-02f93f3cd066a3931
        - sg-086faa640c036bc60
        - sg-0b78f8e3fd5fb767d

