version: '3'
volumes:
  node_modules:
services:
  db:
    image: mdillon/postgis
    container_name: db
  rams:
    image: freeradical3/rams:dev
    container_name: shelterly
    volumes:
      - .:/shelterly
      - node_modules:/shelterly/frontend/node_modules
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db
