version: '3'
services:
  db:
    image: mdillon/postgis
    container_name: db
  shelterly:
    image: trevorskaggs/shelterly:dev
    container_name: shelterly
    ports:
      - "80:80"
    depends_on:
      - db

