
- name: Update Fargate Cluster
  vars_prompt:
    - name: build_dir
      prompt: Enter folder to use for docker build.
      private: no
      default: /tmp/shelterly

    - name: image_tag
      prompt: Enter tag for docker image.
      private: no

    - name: secrets_path
      prompt: Enter path to secrets.json
      private: no

    - name: node_vars
      prompt: Enter path to .env file.
      private: no

  hosts: localhost
  gather_facts: False
  tasks:
  - name: Empty build directory
    ansible.builtin.file:
      path: '{{ build_dir }}'
      state: absent
  - name: Git checkout
    git:
      repo: 'https://github.com/trevorskaggs/shelterly.git'
      dest: '{{ build_dir }}'
      version: ansible-deployment
  - name: Copy secrets
    ansible.builtin.copy:
      src: '{{ secrets_path }}'
      dest: '{{ build_dir }}/config/secrets.json'
  - name: Copy node vars
    ansible.builtin.copy:
      src: '{{ node_vars }}'
      dest: '{{ build_dir }}/frontend/.env'
  - name: Build and push to docker hub
    community.general.docker_image:
      name: 'trevorskaggs/shelterly:{{ image_tag }}'
      push: yes
      build:
        path: '{{ build_dir }}'
      source: build
  - name: Get latest task definition revision
    community.aws.ecs_taskdefinition_info:
      task_definition: shelterly
    register: task_definition_facts

  - name: Create task definition
    community.aws.ecs_taskdefinition:
      family: shelterly
      containers:
      - name: shelterly
        image: trevorskaggs/shelterly:{{ image_tag }}
        portMappings:
        - containerPort: 80
          hostPort: 80
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: /ecs/shelterly
            awslogs-region: us-west-2
            awslogs-stream-prefix: ecs
      launch_type: FARGATE
      cpu: "512"
      memory: "1024"
      execution_role_arn: ""
      task_role_arn: ""
      state: present
      revision: '{{ task_definition_facts.revision + 1}}'
      network_mode: awsvpc
  - name: Update ECS service
    community.aws.ecs_service:
      state: present
      name: shelterly
      launch_type: FARGATE
      load_balancers: 
      - targetGroupArn: ""
        containerName: "shelterly"
        containerPort: "80"
      cluster: shelterly
      task_definition: 'shelterly:{{ task_definition_facts.revision + 1}}'
      desired_count: 1
      network_configuration:
        assign_public_ip: yes
        subnets:

        security_groups:

